Update Jenkinsfile_lab7

diff --git a/Jenkinsfile_lab7 b/Jenkinsfile_lab7
--- a/Jenkinsfile_lab7
+++ b/Jenkinsfile_lab7
@@ -4,10 +4,19 @@ pipeline {
     environment {
         IMAGE_NAME = "sibykannabcd39/wine_predict_2022bcd0039:latest"
         CONTAINER_NAME = "wine_test_container"
-        API_URL = "http://localhost:8000/predict"
+        NETWORK_NAME = "jenkins_network"
+        API_URL = "http://wine_test_container:8000/predict"
     }
 
     stages {
+
+        stage('Create Network') {
+            steps {
+                sh '''
+                docker network create $NETWORK_NAME || true
+                '''
+            }
+        }
 
         stage('Pull Image') {
             steps {
@@ -22,7 +31,10 @@ pipeline {
             steps {
                 sh '''
                 echo "Starting container..."
-                docker run -d -p 8000:8000 --name $CONTAINER_NAME $IMAGE_NAME
+                docker run -d \
+                  --network $NETWORK_NAME \
+                  --name $CONTAINER_NAME \
+                  $IMAGE_NAME
                 '''
             }
         }
@@ -41,7 +53,8 @@ pipeline {
                 script {
                     def response = sh(
                         script: """
-                        curl -s -X POST http://localhost:8000/predict \
+                        docker run --rm --network $NETWORK_NAME curlimages/curl \
+                        -s -X POST $API_URL \
                         -H "Content-Type: application/json" \
                         -d '{"fixed_acidity":7.4,"volatile_acidity":0.70,"citric_acid":0.00,"residual_sugar":1.9,"chlorides":0.076,"free_sulfur_dioxide":11.0,"total_sulfur_dioxide":34.0,"density":0.9978,"pH":3.51,"sulphates":0.56,"alcohol":9.4}'
                         """,
@@ -51,7 +64,7 @@ pipeline {
                     echo "Valid Response: ${response}"
 
                     if (!response.contains("wine_quality")) {
-                        error(" Prediction field missing!")
+                        error("❌ Prediction field missing!")
                     }
                 }
             }
@@ -62,8 +75,9 @@ pipeline {
                 script {
                     def responseCode = sh(
                         script: """
-                        curl -s -o /dev/null -w "%{http_code}" \
-                        -X POST http://localhost:8000/predict \
+                        docker run --rm --network $NETWORK_NAME curlimages/curl \
+                        -s -o /dev/null -w "%{http_code}" \
+                        -X POST $API_URL \
                         -H "Content-Type: application/json" \
                         -d '{"fixed_acidity":7.4}'
                         """,
@@ -73,7 +87,7 @@ pipeline {
                     echo "Invalid Response Code: ${responseCode}"
 
                     if (responseCode == "200") {
-                        error(" Invalid input should not return 200!")
+                        error("❌ Invalid input should not return 200!")
                     }
                 }
             }
@@ -82,7 +96,6 @@ pipeline {
         stage('Stop Container') {
             steps {
                 sh '''
-                echo "Stopping container..."
                 docker stop $CONTAINER_NAME || true
                 docker rm $CONTAINER_NAME || true
                 '''
